<?php
/**
 * Google Tag Manager
 *
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 * http://www.magepal.com | support@magepal.com
 */
?>
<?php /** @var $block \MagePal\GoogleTagManager\Block\DataLayer **/ ?>
<script type="text/javascript">
window.<?php echo $block->getDataLayerName() ?> = window.<?php echo $block->getDataLayerName() ?> || [];
<?php echo $block->getDataLayer(); ?></script>
