<?php
/**
 * Google Tag Manager
 *
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 * http://www.magepal.com | support@magepal.com
 */
?>
<?php /** @var $block \MagePal\GoogleTagManager\Block\GtmCode **/ ?>

<!-- Google Tag Manager by MagePal -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'<?= '/' . '/' ?>www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','<?php echo $block->getDataLayerName() ?>','<?php echo $block->getAccountId() ?>');</script>
<!-- End Google Tag Manager by MagePal -->
