<?php
/**
 * MagePal Google Tag Manager for Magento 2
 *
 * Copyright © 2016 MagePal. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \MagePal\GoogleTagManager\Block\Tm **/ ?>
<?php $accountId = $block->getAccountId(); ?>

<!-- Google Tag Manager by MagePal -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=<?php echo $accountId ?>"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager by MagePal -->
