<?php
/**
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 * http://www.magepal.com | support@magepal.com
 */

/** @var $block MagePal\GoogleTagManager\Block\DataLayer **/
/** @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer */
$dataLayerName = $block->getDataLayerName();
$accountId = $block->getAccountId();
$containerCode = $block->getEmbeddedCode() ? "+'{$block->getEmbeddedCode()}'" : '';
?>

<!-- Google Tag Manager by MagePal -->
<?php $scriptString = <<<script
window.{$dataLayerName} = window.{$dataLayerName} || [];
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<?php if (!$block->isGdprEnabled() && $block->addJsInHead() && !$block->isAdvancedSettingsEnabled()): ?>
    <?php $scriptString = <<<script
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='{$dataLayerName}'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl{$containerCode};f.parentNode.insertBefore(j,f);
    })(window,document,'script','{$dataLayerName}','{$accountId}');
    script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $block->getDataLayerJs(), false) ?>
<?php endif; ?>

<?php if ($block->isAdvancedSettingsEnabled()): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $block->getAdvancedSettingsJsCode(), false) ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $block->getDataLayerJs(), false) ?>
<?php endif; ?>

<?php if (($block->isGdprEnabled() || !$block->addJsInHead()) && !$block->isAdvancedSettingsEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "*": {
            "magepalGtmDatalayer": {
                "isCookieRestrictionModeEnabled": <?= /* @noEscape */ $block->isCookieRestrictionModeEnabled() ?>,
                "currentWebsite": <?= /* @noEscape */ $block->getCurrentWebsiteId() ?>,
                "cookieName": "<?= /* @noEscape */ $block->getCookieRestrictionName() ?>",
                "dataLayer": "<?= /* @noEscape */ $block->getDataLayerName() ?>",
                "accountId": "<?= /* @noEscape */ $block->getAccountId() ?>",
                "data": <?= /* @noEscape */ $block->getDataLayerJson() ?>,
                "isGdprEnabled": <?= /* @noEscape */ $block->isGdprEnabled() ?>,
                "gdprOption": <?= /* @noEscape */ $block->getGdprOption() ?>,
                "addJsInHeader": <?= /* @noEscape */ $block->addJsInHead() ?>,
                "containerCode": "<?= /* @noEscape */ $block->getEmbeddedCode() ?>"
            }
        }
    }
</script>
<?php else : ?>
<script type="text/x-magento-init">
    {
        "*": {
            "magepalGtmDatalayer": {
                "dataLayer": "<?= /* @noEscape */ $block->getDataLayerName() ?>"
            }
        }
    }
</script>
<?php endif; ?>
<!-- End Google Tag Manager by MagePal -->
