<?php
/**
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 * http://www.magepal.com | support@magepal.com
 */

/** @var $block MagePal\GoogleTagManager\Block\DataLayer **/
$dataLayerName = $block->getDataLayerName();
$accountId = $block->getAccountId();
$containerCode = $block->getEmbeddedCode();
?>

<!-- Google Tag Manager by MagePal -->
<script type="text/javascript">
    window.<?= /* @noEscape */ $dataLayerName ?> = window.<?= /* @noEscape */ $dataLayerName ?> || [];

<?php if (!$block->isGdprEnabled() && $block->addJsInHead() && !$block->isAdvancedSettingsEnabled()): ?>
    <?= /* @noEscape */ $block->getDataLayerJs() ?>
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='<?= /* @noEscape */ $dataLayerName ?>'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl<?= /* @noEscape */ $containerCode ? "+'{$containerCode}'" : '' ?>;f.parentNode.insertBefore(j,f);
    })(window,document,'script','<?= /* @noEscape */ $dataLayerName ?>','<?= /* @noEscape */ $accountId ?>');
<?php endif; ?>
</script>

<?php if ($block->isAdvancedSettingsEnabled()): ?>
    <?= /* @noEscape */ $block->getAdvancedSettingsJsCode() ?>
<?php endif; ?>

<?php if (($block->isGdprEnabled() || !$block->addJsInHead()) && !$block->isAdvancedSettingsEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "*": {
            "magepalGtmDatalayer": {
                "isCookieRestrictionModeEnabled": <?= /* @noEscape */ $block->isCookieRestrictionModeEnabled() ?>,
                "currentWebsite": <?= /* @noEscape */ $block->getCurrentWebsiteId() ?>,
                "cookieName": "<?= /* @noEscape */ $block->getCookieRestrictionName() ?>",
                "dataLayer": "<?= /* @noEscape */ $block->getDataLayerName() ?>",
                "accountId": "<?= /* @noEscape */ $block->getAccountId() ?>",
                "data": <?= /* @noEscape */ $block->getDataLayerJson() ?>,
                "isGdprEnabled": <?= /* @noEscape */ $block->isGdprEnabled() ?>,
                "gdprOption": <?= /* @noEscape */ $block->getGdprOption() ?>,
                "addJsInHeader": <?= /* @noEscape */ $block->addJsInHead() ?>,
                "containerCode": "<?= /* @noEscape */ $block->getEmbeddedCode() ?>"
            }
        }
    }
</script>
<?php else : ?>
<script type="text/x-magento-init">
    {
        "*": {
            "magepalGtmDatalayer": {
                "dataLayer": "<?= /* @noEscape */ $block->getDataLayerName() ?>"
            }
        }
    }
</script>
<?php endif; ?>
<!-- End Google Tag Manager by MagePal -->
